# Arch Linux arm64 compat test image.
# lsiobase/arch provides arm64 Arch Linux (official image is x86_64 only).
FROM lsiobase/arch:latest

ARG PACKAGE_GROUP=x11-base
ARG ZIG_VERSION=0.15.2

RUN pacman -Syu --noconfirm \
    base-devel \
    git \
    curl \
    xz \
    pkgconf \
    xorg-server-xvfb \
    openbox \
    xorg-xprop \
    xorg-xrandr \
    ttf-dejavu \
    libxcb \
    xcb-util \
    xcb-util-wm \
    xcb-util-keysyms \
    xcb-util-renderutil \
    xcb-util-cursor \
    libxkbcommon \
    libxkbcommon-x11 \
    cairo \
    pango \
    && if [ "$PACKAGE_GROUP" = "x11-full" ]; then \
        pacman -S --noconfirm librsvg gdk-pixbuf2 dbus pipewire; \
    fi \
    && pacman -Scc --noconfirm

RUN ARCH=$(uname -m) && \
    curl -fsSL "https://ziglang.org/download/${ZIG_VERSION}/zig-${ARCH}-linux-${ZIG_VERSION}.tar.xz" \
    | tar -xJ -C /opt \
    && ln -s /opt/zig-${ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin/zig

WORKDIR /src
COPY . .

COPY .github-workflows/scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
