# OpenMandriva arm64 compat test image.
# openmandriva/minimal:rolling has arm64 support.
FROM openmandriva/minimal:rolling

ARG PACKAGE_GROUP=x11-base
ARG ZIG_VERSION=0.15.2

RUN dnf install -y \
    gcc \
    make \
    curl \
    xz \
    pkgconfig \
    x11-server-xvfb \
    openbox \
    xprop \
    xrandr \
    # arm64 uses lib64 prefix for xcb packages
    lib64xcb-devel \
    lib64xcb-util-devel \
    lib64xcb-util-wm-devel \
    lib64xcb-util-keysyms-devel \
    lib64xcb-util-renderutil-devel \
    lib64xcb-util-cursor-devel \
    cairo-devel \
    pango-devel \
    && if [ "$PACKAGE_GROUP" = "x11-full" ]; then \
        dnf install -y lib64rsvg2-devel lib64gdk_pixbuf2.0-devel pipewire-devel; \
    fi \
    && dnf clean all

RUN ARCH=$(uname -m) && \
    curl -fsSL "https://ziglang.org/download/${ZIG_VERSION}/zig-${ARCH}-linux-${ZIG_VERSION}.tar.xz" \
    | tar -xJ -C /opt \
    && ln -s /opt/zig-${ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin/zig

WORKDIR /src
COPY . .

COPY .github-workflows/scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
